# Sample .travis.yml for R projects from https://github.com/craigcitro/r-travis

language: c

env:
  global:
    - BIOC_USE_DEVEL="TRUE"

before_install:
  - curl -OL http://raw.github.com/craigcitro/r-travis/master/scripts/travis-tool.sh
  - chmod 755 ./travis-tool.sh
  - ./travis-tool.sh bootstrap

install:
  - ./travis-tool.sh install_bioc_deps

script: ./travis-tool.sh run_tests

after_script:
  - FILE=$(ls -1t *.tar.gz | head -n 1)
  - ./travis-tool.sh install_bioc BiocCheck
  - Rscript -e "library(BiocCheck); BiocCheck(\"${FILE}\")"
  - R CMD BiocCheck \"${FILE}\"

on_failure:
  - ./travis-tool.sh dump_logs

notifications:
  email:
    on_failure: ps562@cam.ac.uk
